services:
  - type: web
    name: my-dotnet-backend
    env: docker
    branch: development
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_HOST
      - key: DB_NAME
      - key: DB_USER
      - key: DB_PASSWORD
