services:
  - type: web
    name: my-dotnet-backend
    env: docker
    branch: development
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        value: "mysql://root:mypassword@localhost:3306/MSB_Database"
