services:
  - type: web
    name: my-dotnet-backend
    env: static
    branch: main
    buildCommand: "dotnet build"
    startCommand: "dotnet run --no-launch-profile --urls=http://0.0.0.0:8080"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: MSB_Database
          property: connectionString
